d_dive_demo/ddive/config/routes.rb
Ddive::Application.routes.draw do

  resources :lessons do
    resources :notes, only: [:create, :destroy]
  end

  root 'lessons#bubble'

  get '/welcome2' => 'lessons#welcome2'
  

end

d_dive_demo/ddive/app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :notes
end

d_dive_demo/ddive/app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :lesson
end

d_dive_demo/ddive/app/controllers/.#lessons_controller.rb
kiyomaru@H.Kiyomaru.2598:1441896683

d_dive_demo/ddive/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

d_dive_demo/ddive/app/controllers/lessons_controller.rb
# -*- coding: utf-8 -*-
class LessonsController < ApplicationController
  layout 'application'

  def index
    @search = Lesson.search(params[:q])
    @lessons = @search.result
  end

  def show
    @lesson = Lesson.find(params[:id])
  end
  
  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to lesson_path(@lesson.id)
    else
      render 'edit'
    end
  end

  def bubble
    render :layout => 'welcome'
  end

  def welcome
    @search = Lesson.search(params[:q])
  end
  
  def welcome2
    @search = Lesson.search(params[:q])
  end
  

  def find
    @search = Lesson.search(params[:q])
    @lessons = @search.result
  end

  private
    def lesson_params
      params[:lesson].permit(:title, :teacher, :season,:time, :room)
    end

end

d_dive_demo/ddive/app/controllers/notes_controller.rb
# -*- coding: utf-8 -*-
class NotesController < ApplicationController
  def create
    @lesson = Lesson.find(params[:lesson_id])
    if params[:lesson_id].blank?
        redirect_to :back
      return
    else
      upload_file = params[:note][:file]
      content = {}
      content[:file] = upload_file.read
      content[:filename] = upload_file.original_filename
      content[:lesson_id] = @lesson.id
      @note = Note.new(content)
      if @note.save
        redirect_to lesson_path(@lesson.id)
      else
        redirect_to lesson_path(@lesson.id)
      end
    end
  end
end

d_dive_demo/ddive/app/helpers/application_helper.rb
module ApplicationHelper
end

d_dive_demo/ddive/app/helpers/lessons_helper.rb
module LessonsHelper
end

d_dive_demo/ddive/app/helpers/notes_helper.rb
module NotesHelper
end

d_dive_demo/ddive/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>D-Dive</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= javascript_include_tag "", "data-turbolinks-track" => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= yield %>

</body>
</html>

d_dive_demo/ddive/app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>D-Dive</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag "welcome", media: "all", "data-turbolinks-track" => true %>
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= javascript_include_tag "bubble", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= yield %>

</body>
</html>

d_dive_demo/ddive/app/views/lessons/bubble.html.erb
<div class="wrapper">
  <div class="title">
	<%= image_tag "DDive2.png" %>
  </div>
  <div class="copy">
	<h3>気になる授業に Let's dive.</h3>
  </div>
  <div class="col-sm-12">
    <button class="button btn btn-default form-control" onclick="start()">
      <%= link_to "Dive", welcome2_path %>
    </button>
  </div>
</div>

d_dive_demo/ddive/app/views/lessons/edit.html.erb
<h1>授業時間と教室情報の変更</h1>

<%= form_for @lesson do |f| %>

<p>
  <%= f.label :授業時間 %>
  <%= f.text_field :time %>
</p>
<p>
  <%= f.label :授業教室 %>
  <%= f.text_field :room %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

d_dive_demo/ddive/app/views/lessons/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>D-Dive</title>
    <link rel="stylesheet" href="./DDiveStyle.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    

  </head>


  <body>
   <div class="wrapper">
   <div class="main">
      <h1>D-Dive</h1>
      <table class="table">
        <thread>
        <tr>
         <th>講義名</th><th>教授</th><th>春/秋</th><th>校地</th><th>時間</th><th>教室</th>
        </tr>
        </thread>
        <tbody>
	  <% if @lessons.any? %>
	  <% @lessons.each do |lesson|  %>
            <tr>
	     <% if lesson.title.length < 10 %>
		<th><%= link_to lesson.title, lesson_path(lesson.id) %></th>
		<% else %>
		<th><%= link_to lesson.title[0,10], lesson_path(lesson.id) %>..</th>
		<% end %>
	     <% if lesson.teacher.length < 10 %>
		<th><%= lesson.teacher %></th>
		<% else %>
		<th><%= lesson.teacher[0,10] %>..</th>
		<% end %>
	     <th><%= lesson.season  %></th>
	     <th><%= lesson.place  %></th>
	     <th><%= lesson.time  %></th>
	     <th><%= lesson.room %></th>
            </tr>
	<% end %>
	<% else %>
	    <tr>
	      <th colspan="6">
		お探しの情報に合う講義は見つかりませんでした
	      </th>
	    </tr>
	<% end %>
          </tbody>
      </table>

   </div> 

  </div>

  </body>
</html>

d_dive_demo/ddive/app/views/lessons/show.html.erb
<div class="wrapper">
  <div class="main">
    <h1>D-Dive</h1>
    <table class="table">
      <thread>
        <tr>
          <th>講義名</th>
          <th>教授</th>
          <th>春/秋</th>
          <th>校地</th>
          <th>時間</th>
          <th>教室</th>
        </tr>
      </thread>
      <tbody>
        <tr>
          <th><%= link_to @lesson.title, @lesson.url %></th>
          <th><%= @lesson.teacher %></th>
          <th><%= @lesson.season  %></th>
          <th><%= @lesson.place  %></th>
          <th><%= @lesson.time  %></th>
          <th><%= @lesson.room %></th>
        </tr>
      </tbody>
    </table>
    <p>
      <%= link_to "時間・教室の編集", edit_lesson_path(@lesson.id) %>
    </p>
    <ul>
      <% if @lesson.notes.any? %>
        <%= @lesson.notes.each do |note|  %>
          <li><%= note.filename %></li>
        <% end %> 
      <% else %>
        <p>講義ノートはアップロードされていません</p>
      <% end %>
      <li>
        <%= form_for [@lesson, @lesson.notes.build] do |f| %>
          <%= f.file_field :file %>
          <%= f.submit %>
        <% end %>
      </li>
    </ul>
  </div> 
</div>

d_dive_demo/ddive/app/views/lessons/welcome.html.erb
<h1>Welcome to D-Dive</h1>

<ul>
  <%= search_form_for @search do |f| %>
    <li><%= f.label :title_cont, '講義名' %>
        <%= f.search_field :title_cont %></li>
    <li><%= f.label :teacher_cont, '教授名' %>
        <%= f.search_field :teacher_cont %></li>
    <li><%= f.label :season_cont, '学期　' %>
        <%= f.search_field :season_cont %></li>
    <li><%= f.label :place_cont, '校地　' %>
        <%= f.search_field :place_cont %></li>
    <li><%= f.label :time_cont, '時間　' %>
        <%= f.search_field :time_cont %></li>
</ul>
  <div>
    <%= f.submit '検索' %>
  </div>
<% end %>

d_dive_demo/ddive/app/views/lessons/welcome2.html.erb
<%= search_form_for @search do |f| %>
 <div class="wrapper">
    <div class="header">
     <h1>D-Dive</h1>
    <form class="form-horizontal">
      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-1">
	  <%= f.search_field(:title_cont, class: "form-control", id: "inputTeacher", placeholder: "講義名") %>
	  <%= f.search_field(:teacher_cont, class: "form-control", id: "inputTeacher", placeholder: "教授名") %>
	  <%= f.search_field(:season_cont, class: "form-control", id: "inputTeacher", placeholder: "春 / 秋") %>
          <%= f.search_field(:time_cont, class: "form-control", id: "inputTeacher", placeholder: "例 : 金１") %>
        </div>
      </div>
      <div class="form-group2">
        <div class="col-sm-12">
          <button type="search" class="btn btn-default form-control"><i class=" glyphicon glyphicon-search"></i>検索</button>
        </div>
      </div>
　　  </form>
    </div>
  </div>
<% end %>